package com.busreservation.service;

import org.springframework.stereotype.Service;

@Service
public class CarbonFootprintService {

    // Emission factors in kg CO2 per passenger-km
    private static final double CAR_EMISSION_FACTOR = 0.192;
    private static final double BUS_EMISSION_FACTOR = 0.027;

    /**
     * Calculate CO2 saved by choosing bus over car for a given distance and number
     * of passengers.
     * 
     * @param distanceKm Distance in kilometers
     * @param passengers Number of passengers
     * @return CO2 saved in kg
     */
    public double calculateCO2Saved(double distanceKm, int passengers) {
        if (distanceKm <= 0 || passengers <= 0) {
            return 0.0;
        }
        double carEmissions = distanceKm * CAR_EMISSION_FACTOR * passengers;
        double busEmissions = distanceKm * BUS_EMISSION_FACTOR * passengers;
        return carEmissions - busEmissions;
    }

    /**
     * Calculate total CO2 emissions generated by the bus trip.
     * 
     * @param distanceKm Distance in kilometers
     * @param passengers Number of passengers
     * @return CO2 generated in kg
     */
    public double calculateBusEmissions(double distanceKm, int passengers) {
        if (distanceKm <= 0 || passengers <= 0) {
            return 0.0;
        }
        return distanceKm * BUS_EMISSION_FACTOR * passengers;
    }
}
